### ISSUE TITLE
Lib Crash 

### ISSUE THREAD

**Issue by JeffersonAlmeida** [axiros/AXACT.AndroidSample#1]
Utilizando essa chave o app dar crash:

String value = "zptkrc8uJaud1spndstrqhCwb/MGaAj72Oiv2WcU43EaawEHu1bGoqrbLdpqF/EQX1ChYOT7dUuKYssVivAHcQ==";

Utilizando essa chave o app não dar crash:

 String value = "YpZYIAXwSWP5zKpsVRp8eM5Y7dFl9RY+F07Q2OUdx7x1dvZMsiBBg6BqbGwGsWSS3VinmLFweXSepmIrCG1lgg==";

Crash abaixo:

at java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String) (AXACTJNI.java:-2)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.String com.axiros.axact.AXACT.verify(java.lang.String) (AXACT.java:37)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at int com.axiros.axact.AxirosService.onStartCommand(android.content.Intent, int, int) (AxirosService.java:567)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]     from java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 000202bd  /data/app/br.com.nextel.ecommerce-2/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 0013acd9  /data/app/br.com.nextel.ecommerce-2/oat/arm/base.odex (Java_com_axiros_axact_AXACTJNI_verify__Ljava_lang_String_2+92)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:44:56.303 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:44:56.731 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #16 pc 000202bd  /data/app/br.com.nextel.ecommerce-2/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:44:56.731 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #17 pc 0013acd9  /data/app/br.com.nextel.ecommerce-2/oat/arm/base.odex (Java_com_axiros_axact_AXACTJNI_verify__Ljava_lang_String_2+92)
07-26 10:44:56.731 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:44:56.731 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:44:56.731 21173-21173/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)

art/runtime/java_vm_ext.cc:470]   at java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String) (AXACTJNI.java:-2)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.String com.axiros.axact.AXACT.verify(java.lang.String) (AXACT.java:37)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at int com.axiros.axact.AxirosService.onStartCommand(android.content.Intent, int, int) (AxirosService.java:567)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]     from java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 0013acd9  /data/app/br.com.nextel.ecommerce-1/oat/arm/base.odex (Java_com_axiros_axact_AXACTJNI_verify__Ljava_lang_String_2+92)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:35:19.202 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #14 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String) (AXACTJNI.java:-2)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at java.lang.String com.axiros.axact.AXACT.verify(java.lang.String) (AXACT.java:37)
07-26 10:35:19.497 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at int com.axiros.axact.AxirosService.onStartCommand(android.content.Intent, int, int) (AxirosService.java:567)
07-26 10:35:19.498 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #16 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:19.498 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #17 pc 0013acd9  /data/app/br.com.nextel.ecommerce-1/oat/arm/base.odex (Java_com_axiros_axact_AXACTJNI_verify__Ljava_lang_String_2+92)
07-26 10:35:19.498 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:35:19.498 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:35:19.498 10519-10519/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:35:19.660 10595-10595/? A/DEBUG:     #15 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:22.891 2610-4506/? W/ActivityManager: Scheduling restart of crashed service br.com.nextel.ecommerce/com.axiros.axact.AxirosService in 8854ms
07-26 10:35:31.762 2610-2920/? I/ActivityManager: Start proc 10636:br.com.nextel.ecommerce/u0a490 for service br.com.nextel.ecommerce/com.axiros.axact.AxirosService
07-26 10:35:32.297 10636-10636/br.com.nextel.ecommerce D/com.axiros.axact: AxirosService created.
07-26 10:35:32.308 10636-10636/br.com.nextel.ecommerce D/com.axiros.axact: CA Certs: /data/user/0/br.com.nextel.ecommerce/files/cwmp/cacerts.pem
07-26 10:35:32.310 10636-10636/br.com.nextel.ecommerce I/com.axiros.axact: Turned on logcat logging
07-26 10:35:32.315 10636-10636/br.com.nextel.ecommerce I/com.axiros.axact: Verifing integrator key
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String) (AXACTJNI.java:-2)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.String com.axiros.axact.AXACT.verify(java.lang.String) (AXACT.java:37)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at int com.axiros.axact.AxirosService.onStartCommand(android.content.Intent, int, int) (AxirosService.java:567)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]     from java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 0013acd9  /data/app/br.com.nextel.ecommerce-1/oat/arm/base.odex (Java_com_axiros_axact_AXACTJNI_verify__Ljava_lang_String_2+92)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:35:32.351 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/java_vm_ext.cc:470]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:35:32.606 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #14 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:32.606 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:35:32.606 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:35:32.606 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at java.lang.String com.axiros.axact.AXACTJNI.verify(java.lang.String) (AXACTJNI.java:-2)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at java.lang.String com.axiros.axact.AXACT.verify(java.lang.String) (AXACT.java:37)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at int com.axiros.axact.AxirosService.onStartCommand(android.content.Intent, int, int) (AxirosService.java:567)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #16 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   native: #17 pc 0013acd9  /data/app/br.com.nextel.ecommerce-1/oat/arm/base.odex (Java_com_axiros_axact_AXACTJNI_verify__Ljava_lang_String_2+92)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACTJNI.verify(Native method)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AXACT.verify(AXACT.java:37)
07-26 10:35:32.607 10636-10636/br.com.nextel.ecommerce A/art: art/runtime/runtime.cc:441]   at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:567)
07-26 10:35:32.739 10720-10720/? A/DEBUG:     #15 pc 000202bd  /data/app/br.com.nextel.ecommerce-1/lib/arm/libaxact_shared.so (Java_com_axiros_axact_AXACTJNI_verify+424)

**Comment by cderivan** [comment]
Ola Jefferson,
Eu consegui reproduzir esse erro, infelizmente a chave de decriptografia interna foi mudada e as versões 7 e 8 nao sao mais compatíveis.

Estou gerando uma versão nova, que ao invés de crash ira mostrar a mensagem:
chave do integrador invalida.

**Comment by cderivan** [comment]
fixed in version 009, added message "invalid integration key" 

07-28 12:24:05.980 5092-5092/com.axiros.axactservice D/com.axiros.axact: AxirosService created.
07-28 12:24:06.280 5092-5099/com.axiros.axactservice W/art: Suspending all threads took: 53.276ms
07-28 12:24:06.337 5092-5092/com.axiros.axactservice D/com.axiros.axact: CA Certs: /data/data/com.axiros.axactservice/files/cwmp/eaq.com.br.crt
07-28 12:24:06.363 5092-5092/com.axiros.axactservice I/com.axiros.axact: Verifing integrator key
07-28 12:24:06.433 5092-5092/com.axiros.axactservice E/com.axiros.axact: Integrator key is invalid
07-28 12:24:06.438 5092-5308/com.axiros.axactservice D/com.axiros.axact: AxirosService handle message.
