### ISSUE TITLE
Lib Crash - Unable to start service 

### ISSUE THREAD

**Issue by JeffersonAlmeida** [axiros/AXACT.AndroidSample#2]
java.lang.RuntimeException: Unable to start service com.axiros.axact.AxirosService@cd6b3dc with Intent { cmp=br.com.nextel.ecommerce/com.axiros.axact.AxirosService (has extras)
                             }: java.lang.NullPointerException: println needs a message
                         E      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3335)
                         E      at android.app.ActivityThread.-wrap21(ActivityThread.java)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6123)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                         E  Caused by: java.lang.NullPointerException: println needs a message
                         E      at android.util.Log.println_native_inner(Native Method)
                         E      at android.util.Log.println_native(Log.java:294)
                         E      at android.util.Log.e(Log.java:420)
                         E      at com.axiros.axact.AxirosService.createCWMP(AxirosService.java:475)
                         E      at com.axiros.axact.AxirosService.onStartCommand(AxirosService.java:556)
                         E      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3318)
                         E      ... 8 more

**Comment by cderivan** [comment]
Jefersson consegui reproduzi, acontece que operadoras que ainda nao possuem URL propria nao tem certificado proprio ainda a versao 008 ja pede certificado, a versao 009 verificara se o integrador passou certificado ou nao.

Att,

**Comment by cderivan** [comment]
fixed in release 009
