### ISSUE TITLE
Problem permissions Oreo AXACT

### ISSUE THREAD

**Issue by caioschristino** [axiros/AXACT.AndroidSample#5]
Hi guys! I'm developing with AXACT lib support
I upgraded my app to Android Oreo and when i reboot my smartphone, the app try run the background services but show this crash.

> Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=br.com.app/com.axiros.axact.AxirosService }: app is in background uid UidRecord{55ecd63 u0a200 RCVR idle change:uncached procs:1 seq(0,0,0)}

I maked a review in permissions but can not solve the problem .. Someone can be help me? 
Tnks

**Comment by caioschristino** [comment]
I get the AXACT.AndroidSample and upgrade the gradle to oreo and when reboot the smartphone. 
When the service is started in background, show same IllegalStateException

**Comment by rsfreitas** [comment]
Hi @caioschristino,

We just released a new AXACT library release (v017.1) with this issue fixed.
Update your version and let us know if this behavior is fixed.

Ok?

**Comment by caioschristino** [comment]
Ok tnks! 
Its working now! 

;D
