### ISSUE TITLE
Grandes problemas com a versão 020

### ISSUE THREAD

**Issue by mariosampaioneto** [axiros/AXACT.AndroidSample#7]
Bom dia.

Desde o dia 21/04/19 estamos enfrentando um número muito acima do normal de erros vindos da lib.

Esses erros não são capturados pelo crashlytics. Ocorrem antes da inicialização da MainApplication. Arquivos de stacks da play store estão em anexo

<img width="946" alt="Captura de Tela 2019-05-07 às 15 42 06" src="https://user-images.githubusercontent.com/7727101/57357501-715d4500-7149-11e9-9b69-74480aac4ced.png">
<img width="950" alt="Captura de Tela 2019-05-07 às 15 41 48" src="https://user-images.githubusercontent.com/7727101/57357502-71f5db80-7149-11e9-841c-f98b19cbfd01.png">
<img width="980" alt="Captura de Tela 2019-05-07 às 00 08 10" src="https://user-images.githubusercontent.com/7727101/57357503-71f5db80-7149-11e9-8b86-fcacea6ce80f.png">
<img width="975" alt="Captura de Tela 2019-05-07 às 00 07 58" src="https://user-images.githubusercontent.com/7727101/57357504-71f5db80-7149-11e9-87d9-cbe0ab462bb4.png">

**Comment by rsfreitas** [comment]
Olá @mariosampaioneto 

Obrigado pelo reporte. Estaremos investigando-o e eventualmente
corrigindo-o.

Ok?

**Comment by mariosampaioneto** [comment]
Também estamos em contato com a Oi/ABR para solução desse problema. O Bug está afetando mais de 3 milhões de usuários por mês
